/*
 * BhashaDefaultView.java
 *
 * Created on February 22, 2004, 1:15 AM
 */

package com.swayam.bhasha.oldview.impl;

import java.util.Locale;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import com.swayam.bhasha.engine.io.writers.DocGenerationException;
import com.swayam.bhasha.engine.io.writers.impl.XHtmlGenerator;
import com.swayam.bhasha.oldview.PageContainer;
import com.swayam.bhasha.oldview.io.GenerateOutput;

@SuppressWarnings("serial")
public class BhashaDefaultFrame extends JFrame {

    private final BhashaDefaultPanelView bhashaView;

    private final JTextArea rawHtmlView;

    private final JScrollPane rawHtmlViewPane;

    public BhashaDefaultFrame(PageContainer pageContainer, Locale[] supportedLanguages, Locale defaultLocale) {
	bhashaView = new BhashaDefaultPanelView(this, pageContainer, supportedLanguages, defaultLocale);
	bhashaView.setPageContainer(pageContainer);

	ImageIcon img = new ImageIcon(getClass().getResource("/images/BanglaLogo.jpg"));
	setIconImage(img.getImage());
	initComponents();

	tabbedPane.addTab("Editor View", bhashaView);

	rawHtmlViewPane = new JScrollPane();
	rawHtmlView = new JTextArea();
	rawHtmlView.setEditable(false);
	rawHtmlViewPane.setViewportView(rawHtmlView);

	tabbedPane.addTab("Raw HTML View", rawHtmlViewPane);

	tabbedPane.addChangeListener(new ChangeListener() {

	    public void stateChanged(ChangeEvent e) {

		if (tabbedPane.getSelectedComponent() == rawHtmlViewPane) {
		    try {
			XHtmlGenerator htmlGenerator = new XHtmlGenerator(GenerateOutput.getPageModels(bhashaView.getPageContainer().getPageVector()));
			String html = htmlGenerator.getHtml();
			rawHtmlView.setText(html);
		    } catch (DocGenerationException e1) {
			e1.printStackTrace();
		    }
		}

	    }
	});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	tabbedPane = new javax.swing.JTabbedPane();

	setTitle("Bhasha");
	addWindowListener(new java.awt.event.WindowAdapter() {
	    @Override
	    public void windowClosing(java.awt.event.WindowEvent evt) {
		exitForm(evt);
	    }
	});
	getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

	setJMenuBar(new BhashaMenuBar(bhashaView));

	setBounds(2, 2, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {// GEN-FIRST:
	// event_exitForm
	System.exit(0);
    }// GEN-LAST:event_exitForm

    private javax.swing.JTabbedPane tabbedPane;

    // End of variables declaration//GEN-END:variables

}
